// TileForge — Game Data Definitions
"use strict";

const ERAS = ['caveman','ancient','classical','medieval','renaissance','industrial','modern','ai','mars'];
const ERA_NAMES = {caveman:'Caveman',ancient:'Ancient',classical:'Classical',medieval:'Medieval',renaissance:'Renaissance',industrial:'Industrial',modern:'Modern',ai:'AI',mars:'Mars'};
const ERA_ICONS = {caveman:'🦴',ancient:'⚔️',classical:'🏛️',medieval:'🏰',renaissance:'🔭',industrial:'🏭',modern:'⚡',ai:'🤖',mars:'🚀'};

const MAP_SIZES = {
  small:  {eqWidth:48, rows:32},
  medium: {eqWidth:72, rows:48},
  large:  {eqWidth:96, rows:64}
};

const CIV_COLORS = [
  '#e94560','#2196f3','#4caf50','#ff9800','#9c27b0','#00bcd4','#795548','#607d8b'
];

// Terrain types — id, name, emoji, mvCost (99=impassable), food, prod, gold, defense%, climate zone
const TERRAINS = [
  {id:0,  name:'Ice Sheet',     emoji:'🧊', mv:99, food:0, prod:0, gold:0, def:0,   zone:'polar',    water:false, color:0xE8F0FF},
  {id:1,  name:'Tundra',        emoji:'❄️', mv:1,  food:1, prod:0, gold:0, def:0,   zone:'polar',    water:false, color:0xC8D8D0},
  {id:2,  name:'Taiga',         emoji:'🌲', mv:2,  food:1, prod:2, gold:0, def:25,  zone:'cold',     water:false, color:0x2D5A3D},
  {id:3,  name:'Frozen Coast',  emoji:'🏔️', mv:1,  food:1, prod:0, gold:0, def:0,   zone:'cold',     water:true,  color:0x8BA8C0},
  {id:4,  name:'Grassland',     emoji:'🌿', mv:1,  food:2, prod:0, gold:0, def:0,   zone:'temperate',water:false, color:0x7AB648},
  {id:5,  name:'Plains',        emoji:'🌾', mv:1,  food:1, prod:1, gold:0, def:0,   zone:'temperate',water:false, color:0xA8B060},
  {id:6,  name:'Forest',        emoji:'🌳', mv:2,  food:1, prod:2, gold:0, def:25,  zone:'temperate',water:false, color:0x3A7D3A},
  {id:7,  name:'Hills',         emoji:'⛰️', mv:2,  food:0, prod:2, gold:0, def:50,  zone:'temperate',water:false, color:0x8B7355},
  {id:8,  name:'Mountains',     emoji:'🏔️', mv:99, food:0, prod:1, gold:0, def:0,   zone:'temperate',water:false, color:0x6B6B7B},
  {id:9,  name:'Wetland',       emoji:'🌊', mv:3,  food:2, prod:0, gold:0, def:-25, zone:'temperate',water:false, color:0x5A8A6A},
  {id:10, name:'Desert',        emoji:'🏜️', mv:1,  food:0, prod:0, gold:0, def:0,   zone:'arid',     water:false, color:0xD4C088},
  {id:11, name:'Savanna',       emoji:'🌴', mv:1,  food:1, prod:0, gold:1, def:0,   zone:'arid',     water:false, color:0xB8A848},
  {id:12, name:'Mesa',          emoji:'🏜️', mv:2,  food:0, prod:1, gold:1, def:50,  zone:'arid',     water:false, color:0xC88850},
  {id:13, name:'Oasis',         emoji:'🏝️', mv:1,  food:3, prod:0, gold:1, def:0,   zone:'arid',     water:false, color:0x60B068},
  {id:14, name:'Jungle',        emoji:'🌴', mv:3,  food:2, prod:1, gold:0, def:25,  zone:'tropical', water:false, color:0x1A6030},
  {id:15, name:'Volcanic',      emoji:'🌋', mv:2,  food:0, prod:3, gold:0, def:25,  zone:'tropical', water:false, color:0x5A3030},
  {id:16, name:'Coast',         emoji:'🌊', mv:1,  food:1, prod:0, gold:1, def:0,   zone:'water',    water:true,  color:0x4488BB},
  {id:17, name:'Ocean',         emoji:'🌊', mv:1,  food:0, prod:0, gold:1, def:0,   zone:'water',    water:true,  color:0x2266AA},
  {id:18, name:'Reef',          emoji:'🐚', mv:1,  food:2, prod:0, gold:1, def:0,   zone:'water',    water:true,  color:0x40A0A8},
  {id:19, name:'River Delta',   emoji:'🏞️', mv:1,  food:3, prod:0, gold:2, def:-25, zone:'tropical', water:false, color:0x60A060}
];

// Resources — name, type (bonus/luxury/strategic), yields, terrainIds where they spawn
const RESOURCES = [
  // Bonus
  {id:'wheat',    name:'Wheat',    type:'bonus',    food:2,prod:0,gold:0,sci:0, terrains:[4,5]},
  {id:'cattle',   name:'Cattle',   type:'bonus',    food:1,prod:1,gold:0,sci:0, terrains:[4,5]},
  {id:'fish',     name:'Fish',     type:'bonus',    food:2,prod:0,gold:0,sci:0, terrains:[16,18]},
  {id:'deer',     name:'Deer',     type:'bonus',    food:1,prod:1,gold:0,sci:0, terrains:[6,2]},
  {id:'stone',    name:'Stone',    type:'bonus',    food:0,prod:2,gold:0,sci:0, terrains:[7,8]},
  {id:'timber',   name:'Timber',   type:'bonus',    food:0,prod:2,gold:0,sci:0, terrains:[2,6]},
  {id:'maize',    name:'Maize',    type:'bonus',    food:3,prod:0,gold:0,sci:0, terrains:[5,4]},
  {id:'rice',     name:'Rice',     type:'bonus',    food:3,prod:0,gold:0,sci:0, terrains:[9,19]},
  {id:'bananas',  name:'Bananas',  type:'bonus',    food:3,prod:0,gold:0,sci:0, terrains:[14]},
  {id:'papyrus',  name:'Papyrus',  type:'bonus',    food:0,prod:0,gold:1,sci:2, terrains:[19]},
  {id:'marble',   name:'Marble',   type:'bonus',    food:0,prod:2,gold:0,sci:0, terrains:[8,7]},
  {id:'wood',     name:'Wood',     type:'bonus',    food:1,prod:1,gold:0,sci:0, terrains:[2,6]},
  {id:'sheep',    name:'Sheep',    type:'bonus',    food:1,prod:0,gold:1,sci:0, terrains:[4,5]},
  {id:'hardwood', name:'Hardwood', type:'bonus',    food:0,prod:2,gold:1,sci:0, terrains:[6]},
  {id:'granite',  name:'Granite',  type:'bonus',    food:0,prod:2,gold:0,sci:0, terrains:[12]},
  {id:'mammoth_bones',name:'Mammoth Bones',type:'bonus',food:0,prod:2,gold:0,sci:0,cul:1, terrains:[1]},
  {id:'peat',     name:'Peat',     type:'bonus',    food:0,prod:2,gold:0,sci:0, terrains:[1]},
  {id:'whale',    name:'Whale',    type:'bonus',    food:2,prod:0,gold:1,sci:0, terrains:[3]},
  {id:'seal',     name:'Seal',     type:'bonus',    food:1,prod:0,gold:1,sci:0, terrains:[3]},
  {id:'tuna',     name:'Tuna',     type:'bonus',    food:3,prod:0,gold:0,sci:0, terrains:[17]},
  {id:'crab',     name:'Crab',     type:'bonus',    food:1,prod:0,gold:1,sci:0, terrains:[16]},
  {id:'shellfish',name:'Shellfish', type:'bonus',   food:2,prod:0,gold:1,sci:0, terrains:[18]},
  {id:'dates',    name:'Dates',    type:'bonus',    food:2,prod:0,gold:1,sci:0, terrains:[13]},
  {id:'citrus',   name:'Citrus',   type:'bonus',    food:2,prod:0,gold:1,sci:0, terrains:[11]},
  {id:'flax',     name:'Flax',     type:'bonus',    food:1,prod:0,gold:1,sci:0, terrains:[19]},
  {id:'sandstone',name:'Sandstone', type:'bonus',   food:0,prod:2,gold:0,sci:0,cul:1, terrains:[10,12]},
  {id:'glass_sand',name:'Glass Sand',type:'bonus',  food:0,prod:1,gold:1,sci:0, terrains:[10]},
  // Luxury
  {id:'gold_ore', name:'Gold',     type:'luxury',   food:0,prod:0,gold:4,sci:0, terrains:[7,8]},
  {id:'silver',   name:'Silver',   type:'luxury',   food:0,prod:0,gold:3,sci:0, terrains:[8]},
  {id:'gems',     name:'Gems',     type:'luxury',   food:0,prod:0,gold:4,sci:0, terrains:[15]},
  {id:'spices',   name:'Spices',   type:'luxury',   food:1,prod:0,gold:2,sci:0, terrains:[14,11]},
  {id:'silk',     name:'Silk',     type:'luxury',   food:0,prod:0,gold:3,sci:0, terrains:[13]},
  {id:'wine',     name:'Wine',     type:'luxury',   food:1,prod:0,gold:2,sci:0, terrains:[7,5]},
  {id:'furs',     name:'Furs',     type:'luxury',   food:0,prod:0,gold:2,sci:0, terrains:[2,1]},
  {id:'cotton',   name:'Cotton',   type:'luxury',   food:0,prod:1,gold:2,sci:0, terrains:[4,5]},
  {id:'incense',  name:'Incense',  type:'luxury',   food:0,prod:0,gold:2,sci:0, terrains:[10,11]},
  {id:'salt',     name:'Salt',     type:'luxury',   food:1,prod:0,gold:2,sci:0, terrains:[10,12]},
  {id:'coffee',   name:'Coffee',   type:'luxury',   food:0,prod:0,gold:2,sci:1, terrains:[11,14]},
  {id:'tea',      name:'Tea',      type:'luxury',   food:0,prod:0,gold:2,sci:1, terrains:[7]},
  {id:'amber',    name:'Amber',    type:'luxury',   food:0,prod:0,gold:2,sci:0,cul:1, terrains:[1]},
  {id:'aurora_crystals',name:'Aurora Crystals',type:'luxury',food:0,prod:0,gold:3,sci:2, terrains:[0]},
  {id:'truffles', name:'Truffles', type:'luxury',   food:0,prod:0,gold:3,sci:0, terrains:[6]},
  {id:'tobacco',  name:'Tobacco',  type:'luxury',   food:0,prod:0,gold:2,sci:0, terrains:[5]},
  {id:'ivory',    name:'Ivory',    type:'luxury',   food:0,prod:0,gold:2,sci:0,cul:1, terrains:[11]},
  {id:'jade',     name:'Jade',     type:'luxury',   food:0,prod:0,gold:2,sci:0,cul:1, terrains:[8]},
  {id:'dye',      name:'Dye',      type:'luxury',   food:0,prod:0,gold:2,sci:0,cul:1, terrains:[14]},
  {id:'sugar_cane',name:'Sugar Cane',type:'luxury', food:1,prod:0,gold:2,sci:0, terrains:[14,9]},
  {id:'coral_dye',name:'Coral Dye', type:'luxury',  food:0,prod:0,gold:2,sci:0,cul:1, terrains:[18]},
  {id:'salt_flats',name:'Salt Flats',type:'luxury', food:0,prod:0,gold:2,sci:0, terrains:[16]},
  {id:'medicinal_herbs',name:'Medicinal Herbs',type:'luxury',food:1,prod:0,gold:0,sci:2, terrains:[9]},
  {id:'pearl',    name:'Pearl',    type:'luxury',   food:0,prod:0,gold:3,sci:0, terrains:[17]},
  // Strategic
  {id:'horses',   name:'Horses',   type:'strategic',food:1,prod:1,gold:0,sci:0, terrains:[5,4],  revealTech:'animal_husbandry'},
  {id:'copper',   name:'Copper',   type:'strategic',food:0,prod:2,gold:0,sci:0, terrains:[12,7], revealTech:'bronze_working'},
  {id:'iron',     name:'Iron',     type:'strategic',food:0,prod:2,gold:0,sci:0, terrains:[7],    revealTech:'iron_working'},
  {id:'coal',     name:'Coal',     type:'strategic',food:0,prod:2,gold:0,sci:0, terrains:[2,7],  revealTech:'steam_power'},
  {id:'niter',    name:'Niter',    type:'strategic',food:0,prod:2,gold:0,sci:0, terrains:[10],   revealTech:'gunpowder'},
  {id:'oil',      name:'Oil',      type:'strategic',food:0,prod:3,gold:0,sci:0, terrains:[10,17],revealTech:'combustion'},
  {id:'uranium',  name:'Uranium',  type:'strategic',food:0,prod:2,gold:0,sci:1, terrains:[10,7], revealTech:'nuclear_fission'},
  {id:'aluminum', name:'Aluminum', type:'strategic',food:0,prod:2,gold:0,sci:0, terrains:[14,7], revealTech:'industrialization'},
  {id:'flint',    name:'Flint',    type:'strategic',food:0,prod:1,gold:0,sci:0, terrains:[1,4,7], revealTech:'stone_knapping'},
  {id:'tin',      name:'Tin',      type:'strategic',food:0,prod:1,gold:1,sci:0, terrains:[7,12,19], revealTech:'bronze_working'},
  {id:'zinc',     name:'Zinc',     type:'strategic',food:0,prod:1,gold:1,sci:0, terrains:[7], revealTech:'currency'},
  {id:'limestone',name:'Limestone', type:'strategic',food:0,prod:2,gold:0,sci:0, terrains:[7], revealTech:'construction'},
  {id:'clay',     name:'Clay',     type:'strategic',food:0,prod:1,gold:0,sci:1, terrains:[9,19], revealTech:'pottery'},
  {id:'obsidian', name:'Obsidian', type:'strategic',food:0,prod:2,gold:0,sci:1, terrains:[15], revealTech:'stone_knapping'},
  {id:'lead',     name:'Lead',     type:'strategic',food:0,prod:1,gold:0,sci:0, terrains:[7], revealTech:'gunpowder'},
  {id:'sulfur',   name:'Sulfur',   type:'strategic',food:0,prod:2,gold:0,sci:0, terrains:[15], revealTech:'gunpowder'},
  {id:'bauxite',  name:'Bauxite',  type:'strategic',food:0,prod:2,gold:0,sci:0, terrains:[14], revealTech:'industrialization'},
  {id:'rubber',   name:'Rubber',   type:'strategic',food:0,prod:1,gold:0,sci:0, terrains:[9], revealTech:'industrialization'},
  {id:'chromium', name:'Chromium', type:'strategic',food:0,prod:1,gold:0,sci:1, terrains:[7], revealTech:'industrialization'},
  {id:'manganese',name:'Manganese',type:'strategic',food:0,prod:1,gold:0,sci:0, terrains:[8], revealTech:'industrialization'},
  {id:'tungsten', name:'Tungsten', type:'strategic',food:0,prod:2,gold:1,sci:0, terrains:[15], revealTech:'industrialization'},
  {id:'nickel',   name:'Nickel',   type:'strategic',food:0,prod:1,gold:1,sci:0, terrains:[15], revealTech:'industrialization'},
  {id:'phosphate',name:'Phosphate',type:'strategic',food:0,prod:1,gold:0,sci:0, terrains:[10,11], revealTech:'industrialization'},
  {id:'silicon',  name:'Silicon',  type:'strategic',food:0,prod:1,gold:0,sci:2, terrains:[10], revealTech:'electronics'},
  {id:'lithium',  name:'Lithium',  type:'strategic',food:0,prod:1,gold:0,sci:2, terrains:[10,12], revealTech:'electronics'},
  {id:'cobalt',   name:'Cobalt',   type:'strategic',food:0,prod:2,gold:0,sci:1, terrains:[14], revealTech:'electronics'},
  {id:'graphite', name:'Graphite', type:'strategic',food:0,prod:1,gold:0,sci:1, terrains:[1,8], revealTech:'nuclear_fission'},
  {id:'titanium', name:'Titanium', type:'strategic',food:0,prod:2,gold:0,sci:0, terrains:[8], revealTech:'robotics'},
  {id:'neodymium',name:'Neodymium',type:'strategic',food:0,prod:1,gold:0,sci:2, terrains:[8], revealTech:'robotics'},
  {id:'helium_3', name:'Helium-3', type:'strategic',food:0,prod:3,gold:0,sci:2, terrains:[0], revealTech:'fusion'},
  {id:'geothermal',name:'Geothermal',type:'strategic',food:0,prod:3,gold:0,sci:1, terrains:[15], revealTech:'electricity'},
];

// Composite resources — crafted from two base resources + tech
const COMPOSITES = [
  {id:'brick', name:'Brick', era:'ancient', ingredients:['clay','wood'], tech:'pottery', desc:'+1 Prod all cities'},
  {id:'bronze', name:'Bronze', era:'ancient', ingredients:['copper','tin'], tech:'bronze_working', desc:'Enables Spearman, Forge'},
  {id:'concrete', name:'Concrete', era:'classical', ingredients:['limestone','clay'], tech:'construction', desc:'Enables Aqueduct, Roads -50%'},
  {id:'brass', name:'Brass', era:'classical', ingredients:['copper','zinc'], tech:'currency', desc:'+10% Money empire'},
  {id:'steel_composite', name:'Steel', era:'medieval', ingredients:['iron','coal'], tech:'steel', desc:'Enables Castle, Knight'},
  {id:'gunpowder_composite', name:'Gunpowder', era:'renaissance', ingredients:['niter','sulfur'], tech:'gunpowder', desc:'Enables gunpowder units'},
  {id:'ammunition', name:'Ammunition', era:'renaissance', ingredients:['lead','gunpowder_composite'], tech:'rifling', desc:'Enables bullet-based units'},
  {id:'stainless_steel', name:'Stainless Steel', era:'industrial', ingredients:['steel_composite','chromium'], tech:'industrialization', desc:'Enables Hospital, precision'},
  {id:'aluminum_refined', name:'Aluminum', era:'industrial', ingredients:['bauxite','coal'], tech:'industrialization', desc:'Lightweight construction'},
  {id:'electrical_wire', name:'Electrical Wire', era:'industrial', ingredients:['copper','rubber'], tech:'electricity', desc:'Power grid, Factory upgrade'},
  {id:'fertilizer', name:'Fertilizer', era:'industrial', ingredients:['niter','phosphate'], tech:'industrialization', desc:'+2 Food all farms'},
  {id:'dynamite_composite', name:'Dynamite', era:'industrial', ingredients:['niter','oil'], tech:'dynamite', desc:'Railway, Deep Mine'},
  {id:'plastics', name:'Plastics', era:'modern', ingredients:['oil','rubber'], tech:'combustion', desc:'Modern buildings'},
  {id:'microchips', name:'Microchips', era:'modern', ingredients:['silicon','cobalt'], tech:'electronics', desc:'All AI-era prereq'},
  {id:'batteries', name:'Batteries', era:'modern', ingredients:['lithium','cobalt'], tech:'electronics', desc:'Drones, EVs'},
  {id:'nuclear_fuel', name:'Nuclear Fuel', era:'modern', ingredients:['uranium','graphite'], tech:'nuclear_fission', desc:'Nukes, Nuclear Plant'},
  {id:'fiber_optics', name:'Fiber Optics', era:'modern', ingredients:['glass_sand','silicon'], tech:'telecommunications', desc:'Broadcast Tower, +1 Sci'},
  {id:'jet_fuel', name:'Jet Fuel', era:'modern', ingredients:['aluminum_refined','oil'], tech:'flight', desc:'Jet aircraft'},
  {id:'carbon_fiber', name:'Carbon Fiber', era:'ai', ingredients:['coal','plastics'], tech:'nanotech', desc:'Space construction'},
  {id:'nanomaterials', name:'Nanomaterials', era:'ai', ingredients:['titanium','cobalt'], tech:'nanotech', desc:'Exoskeletons, Titan Mech'},
  {id:'quantum_processors', name:'Quantum Processors', era:'ai', ingredients:['microchips','helium_3'], tech:'quantum', desc:'The Singularity wonder'},
  {id:'fusion_fuel', name:'Fusion Fuel', era:'mars', ingredients:['helium_3','oil'], tech:'fusion', desc:'Fusion Reactor, Mars Shuttle'},
  {id:'orbital_components', name:'Orbital Components', era:'mars', ingredients:['carbon_fiber','titanium'], tech:'orbital', desc:'Space Elevator, Mars'},
];

// Technologies — id, name, era, cost (science), prereqs, unlocks
const TECHS = [
  // Caveman
  {id:'fire',        name:'Fire Making',    era:'caveman',   cost:10,  prereqs:[], unlocks:['firepit']},
  {id:'toolcraft',   name:'Toolcraft',      era:'caveman',   cost:12,  prereqs:['fire'], unlocks:['gathering_camp']},
  {id:'foraging',    name:'Foraging',       era:'caveman',   cost:8,   prereqs:[], unlocks:['gatherer']},
  {id:'stone_knapping',name:'Stone Knapping',era:'caveman',  cost:14,  prereqs:['toolcraft'], unlocks:['stone_circle','palisade']},
  {id:'tribal_bonds',name:'Tribal Bonds',   era:'caveman',   cost:15,  prereqs:['foraging'], unlocks:['nomad','scout']},
  // Ancient
  {id:'agriculture', name:'Agriculture',    era:'ancient',   cost:25,  prereqs:['foraging'], unlocks:['farm','settler','granary']},
  {id:'pottery',     name:'Pottery',        era:'ancient',   cost:20,  prereqs:['fire'], unlocks:['pottery_workshop']},
  {id:'mining',      name:'Mining',         era:'ancient',   cost:22,  prereqs:['toolcraft'], unlocks:['mine','worker']},
  {id:'animal_husbandry',name:'Animal Husbandry',era:'ancient',cost:20,prereqs:['foraging'], unlocks:['pasture','horseman']},
  {id:'bronze_working',name:'Bronze Working',era:'ancient',  cost:30,  prereqs:['mining'], unlocks:['warrior','spearman','barracks']},
  {id:'archery',     name:'Archery',        era:'ancient',   cost:25,  prereqs:['stone_knapping'], unlocks:['archer']},
  {id:'writing',     name:'Writing',        era:'ancient',   cost:35,  prereqs:['pottery'], unlocks:['library']},
  {id:'sailing',     name:'Sailing',        era:'ancient',   cost:28,  prereqs:['toolcraft'], unlocks:['galley','harbor']},
  // Classical
  {id:'iron_working',name:'Iron Working',   era:'classical', cost:50,  prereqs:['bronze_working'], unlocks:['swordsman','forge']},
  {id:'mathematics', name:'Mathematics',    era:'classical', cost:45,  prereqs:['writing'], unlocks:['catapult']},
  {id:'construction',name:'Construction',   era:'classical', cost:55,  prereqs:['mining','mathematics'], unlocks:['walls','aqueduct']},
  {id:'currency',    name:'Currency',       era:'classical', cost:40,  prereqs:['writing'], unlocks:['market','mint']},
  {id:'philosophy',  name:'Philosophy',     era:'classical', cost:48,  prereqs:['writing'], unlocks:['amphitheatre']},
  // Medieval
  {id:'education',   name:'Education',      era:'medieval',  cost:80,  prereqs:['philosophy','mathematics'], unlocks:['university']},
  {id:'steel',       name:'Steel',          era:'medieval',  cost:90,  prereqs:['iron_working'], unlocks:['longswordsman','knight','castle','workshop']},
  {id:'theology',    name:'Theology',       era:'medieval',  cost:70,  prereqs:['philosophy'], unlocks:['cathedral','monastery']},
  {id:'civil_service',name:'Civil Service', era:'medieval',  cost:75,  prereqs:['currency'], unlocks:['bank','town_hall']},
  {id:'navigation',  name:'Navigation',     era:'medieval',  cost:85,  prereqs:['sailing','mathematics'], unlocks:['caravel','shipyard']},
  // Renaissance
  {id:'gunpowder',   name:'Gunpowder',     era:'renaissance',cost:120, prereqs:['steel'], unlocks:['musketman','cannon','arsenal']},
  {id:'printing',    name:'Printing',       era:'renaissance',cost:100, prereqs:['education'], unlocks:['printing_house','school']},
  {id:'astronomy',   name:'Astronomy',      era:'renaissance',cost:110, prereqs:['education','navigation'], unlocks:['observatory']},
  {id:'economics',   name:'Economics',      era:'renaissance',cost:105, prereqs:['currency','civil_service'], unlocks:['stock_exchange','customs_house']},
  {id:'colonialism', name:'Colonialism',    era:'renaissance',cost:115, prereqs:['navigation','gunpowder'], unlocks:['frigate','marine']},
  // Industrial
  {id:'steam_power', name:'Steam Power',    era:'industrial',cost:160, prereqs:['steel','economics'], unlocks:['factory','ironclad']},
  {id:'industrialization',name:'Industrialization',era:'industrial',cost:180,prereqs:['steam_power'], unlocks:['rifleman','railway_station']},
  {id:'electricity', name:'Electricity',    era:'industrial',cost:170, prereqs:['steam_power'], unlocks:['coal_power','hospital']},
  {id:'dynamite',    name:'Dynamite',       era:'industrial',cost:150, prereqs:['gunpowder','steam_power'], unlocks:['artillery']},
  {id:'rifling',     name:'Rifling',        era:'industrial',cost:155, prereqs:['gunpowder','industrialization'], unlocks:['cavalry']},
  {id:'chemistry',   name:'Chemistry',      era:'industrial',cost:165, prereqs:['gunpowder','steam_power'], unlocks:['sewage_works','pharmacy']},
  // Modern
  {id:'combustion',  name:'Combustion',     era:'modern',    cost:220, prereqs:['industrialization'], unlocks:['tank','airport']},
  {id:'flight',      name:'Flight',         era:'modern',    cost:230, prereqs:['combustion'], unlocks:['fighter','bomber']},
  {id:'electronics', name:'Electronics',    era:'modern',    cost:240, prereqs:['electricity'], unlocks:['research_lab','broadcast_tower']},
  {id:'nuclear_fission',name:'Nuclear Fission',era:'modern', cost:280, prereqs:['electronics'], unlocks:['nuclear_plant','tactical_nuke']},
  {id:'telecommunications',name:'Telecom',  era:'modern',    cost:250, prereqs:['electronics'], unlocks:['stadium','comms_tower']},
  {id:'rocketry',    name:'Rocketry',       era:'modern',    cost:260, prereqs:['flight','electronics'], unlocks:['rocket_artillery']},
  {id:'plastics_tech',name:'Plastics',      era:'modern',    cost:235, prereqs:['combustion','electricity'], unlocks:['supermarket','night_club']},
  // AI Era
  {id:'computers',   name:'Computers',      era:'ai',        cost:320, prereqs:['electronics','telecommunications'], unlocks:['data_centre']},
  {id:'robotics',    name:'Robotics',       era:'ai',        cost:340, prereqs:['computers'], unlocks:['drone_factory','mech_walker']},
  {id:'ai_tech',     name:'Machine Learning',era:'ai',       cost:360, prereqs:['computers'], unlocks:['neural_hub','cyber_infantry']},
  {id:'quantum',     name:'Quantum Computing',era:'ai',      cost:400, prereqs:['ai_tech'], unlocks:['quantum_lab']},
  {id:'nanotech',    name:'Nanotech',       era:'ai',        cost:380, prereqs:['robotics'], unlocks:['vertical_farm']},
  {id:'advanced_materials',name:'Advanced Materials',era:'ai',cost:350, prereqs:['nanotech'], unlocks:['firewall','ev_chargers']},
  // Mars Era
  {id:'orbital',     name:'Orbital Construction',era:'mars',  cost:500, prereqs:['quantum','nanotech'], unlocks:['launch_pad','space_dock']},
  {id:'fusion',      name:'Fusion Power',   era:'mars',      cost:550, prereqs:['quantum'], unlocks:['fusion_reactor']},
  {id:'mars_colony', name:'Mars Colony',    era:'mars',      cost:600, prereqs:['orbital','fusion'], unlocks:['mars_shuttle']}
];

// Buildings — id, name, era, cost, requires (tech), yields, effects
const BUILDINGS = [
  // Caveman
  {id:'firepit',     name:'Firepit',     era:'caveman',  cost:10,  req:'fire',         food:1,prod:0,gold:0,sci:0,cul:0,hap:1, desc:'+1 Food, +1 Happy'},
  {id:'stone_circle',name:'Stone Circle', era:'caveman', cost:15,  req:'stone_knapping',food:0,prod:0,gold:0,sci:0,cul:2,hap:1, desc:'+2 Culture, +1 Happy'},
  {id:'palisade',    name:'Palisade',     era:'caveman', cost:12,  req:'stone_knapping',food:0,prod:0,gold:0,sci:0,cul:0,hap:0, desc:'+25% defense', defense:25},
  {id:'flint_workshop',name:'Flint Workshop',era:'caveman',cost:10,req:'stone_knapping',food:0,prod:1,gold:0,sci:0,cul:0,hap:0, desc:'+1 Prod'},
  {id:'burial_mound',name:'Burial Mound', era:'caveman', cost:20,  req:'stone_knapping',food:0,prod:0,gold:0,sci:0,cul:3,hap:0, desc:'+3 Culture, +1 History'},
  // Ancient
  {id:'granary',     name:'Granary',      era:'ancient',  cost:25,  req:'agriculture',  food:2,prod:0,gold:0,sci:0,cul:0,hap:0, desc:'+2 Food, +15% growth', growthMod:0.15},
  {id:'monument',    name:'Monument',     era:'ancient',  cost:20,  req:'mining',       food:0,prod:0,gold:0,sci:0,cul:2,hap:0, desc:'+2 Culture'},
  {id:'walls',       name:'Walls',        era:'ancient',  cost:30,  req:'construction', food:0,prod:0,gold:0,sci:0,cul:0,hap:0, desc:'+50% defense', defense:50},
  {id:'barracks',    name:'Barracks',     era:'ancient',  cost:25,  req:'bronze_working',food:0,prod:1,gold:0,sci:0,cul:0,hap:0, desc:'+1 Prod, +15 XP new units', xpBonus:15},
  {id:'library',     name:'Library',      era:'ancient',  cost:40,  req:'writing',      food:0,prod:0,gold:0,sci:3,cul:0,hap:0, desc:'+3 Science'},
  {id:'harbor',      name:'Harbor',       era:'ancient',  cost:35,  req:'sailing',      food:1,prod:0,gold:2,sci:0,cul:0,hap:0, desc:'+1 Food, +2 Gold (coast)', needsCoast:true},
  {id:'potters_workshop',name:"Potter's Workshop",era:'ancient',cost:20,req:'pottery',  food:0,prod:1,gold:1,sci:0,cul:0,hap:0, desc:'+1 Prod, +1 Gold'},
  {id:'shrine',      name:'Shrine',       era:'ancient',  cost:20,  req:'mining',       food:0,prod:0,gold:0,sci:1,cul:1,hap:1, desc:'+1 Science, +1 Culture, +1 Happy'},
  {id:'well',        name:'Well',         era:'ancient',  cost:15,  req:'mining',       food:1,prod:0,gold:0,sci:0,cul:0,hap:1, desc:'+1 Food, +1 Happy'},
  {id:'storehouse',  name:'Storehouse',   era:'ancient',  cost:25,  req:'pottery',      food:0,prod:1,gold:0,sci:0,cul:0,hap:0, desc:'+1 Prod, carry 50% overflow'},
  {id:'tavern',      name:'Tavern',       era:'ancient',  cost:20,  req:'agriculture',  food:1,prod:0,gold:1,sci:0,cul:0,hap:1, desc:'+1 Food, +1 Gold, +1 Happy'},
  {id:'herbalist',   name:'Herbalist',    era:'ancient',  cost:20,  req:'foraging',     food:1,prod:0,gold:0,sci:1,cul:0,hap:0, desc:'+1 Food, +1 Science'},
  // Classical
  {id:'market',      name:'Market',       era:'classical',cost:35,  req:'currency',     food:0,prod:0,gold:3,sci:0,cul:0,hap:0, desc:'+3 Gold, +25% Gold', goldMod:0.25},
  {id:'forge',       name:'Forge',        era:'classical',cost:35,  req:'iron_working', food:0,prod:2,gold:0,sci:0,cul:0,hap:0, desc:'+2 Prod, +15% unit prod', unitProdMod:0.15},
  {id:'amphitheatre',name:'Amphitheatre', era:'classical',cost:40,  req:'philosophy',   food:0,prod:0,gold:0,sci:0,cul:3,hap:1, desc:'+3 Culture, +1 Happy'},
  {id:'aqueduct',    name:'Aqueduct',     era:'classical',cost:50,  req:'construction', food:0,prod:0,gold:0,sci:0,cul:0,hap:0, desc:'+25% growth', growthMod:0.25},
  {id:'mint',        name:'Mint',         era:'classical',cost:45,  req:'currency',     food:0,prod:0,gold:3,sci:0,cul:0,hap:0, desc:'+3 Gold'},
  {id:'courthouse',  name:'Courthouse',   era:'classical',cost:30,  req:'currency',     food:0,prod:0,gold:1,sci:0,cul:0,hap:0, desc:'-25% corruption'},
  {id:'bath_house',  name:'Bath House',   era:'classical',cost:40,  req:'construction', food:1,prod:0,gold:0,sci:0,cul:0,hap:2, desc:'+1 Food, +2 Happy'},
  {id:'warehouse',   name:'Warehouse',    era:'classical',cost:30,  req:'construction', food:0,prod:2,gold:0,sci:0,cul:0,hap:0, desc:'+2 Prod'},
  {id:'dry_dock',    name:'Dry Dock',     era:'classical',cost:45,  req:'sailing',      food:0,prod:2,gold:0,sci:0,cul:0,hap:0, desc:'+25% naval Prod', needsCoast:true},
  {id:'blacksmith',  name:'Blacksmith',   era:'classical',cost:35,  req:'iron_working', food:0,prod:2,gold:0,sci:0,cul:0,hap:0, desc:'+2 Prod, -10% unit maint'},
  {id:'inn',         name:'Inn',          era:'classical',cost:30,  req:'currency',     food:0,prod:0,gold:2,sci:0,cul:0,hap:2, desc:'+2 Gold, +2 Happy'},
  {id:'public_square',name:'Public Square',era:'classical',cost:25, req:'philosophy',   food:0,prod:0,gold:1,sci:0,cul:1,hap:1, desc:'+1 Gold, +1 Culture, +1 Happy'},
  // Medieval
  {id:'university',  name:'University',   era:'medieval', cost:60,  req:'education',    food:0,prod:0,gold:0,sci:5,cul:0,hap:0, desc:'+5 Science, +33% Science', sciMod:0.33},
  {id:'bank',        name:'Bank',         era:'medieval', cost:55,  req:'civil_service', food:0,prod:0,gold:4,sci:0,cul:0,hap:0, desc:'+4 Gold, +25% Gold', goldMod:0.25},
  {id:'castle',      name:'Castle',       era:'medieval', cost:70,  req:'steel',        food:0,prod:0,gold:0,sci:0,cul:0,hap:0, desc:'+100% defense', defense:100},
  {id:'workshop',    name:'Workshop',     era:'medieval', cost:50,  req:'steel',        food:0,prod:3,gold:0,sci:0,cul:0,hap:0, desc:'+3 Prod, +10% Prod', prodMod:0.10},
  {id:'cathedral',   name:'Cathedral',    era:'medieval', cost:80,  req:'theology',     food:0,prod:0,gold:0,sci:0,cul:3,hap:3, desc:'+3 Culture, +3 Happy'},
  {id:'town_hall',   name:'Town Hall',    era:'medieval', cost:45,  req:'civil_service', food:0,prod:0,gold:2,sci:0,cul:0,hap:1, desc:'+2 Gold, +1 Happy'},
  {id:'guild_hall',  name:'Guild Hall',   era:'medieval', cost:50,  req:'civil_service', food:0,prod:2,gold:2,sci:0,cul:0,hap:0, desc:'+2 Prod, +2 Gold'},
  {id:'monastery',   name:'Monastery',    era:'medieval', cost:45,  req:'theology',     food:0,prod:0,gold:0,sci:2,cul:1,hap:0, desc:'+2 Science, +1 Culture'},
  {id:'gatehouse',   name:'Gatehouse',    era:'medieval', cost:40,  req:'steel',        food:0,prod:0,gold:0,sci:0,cul:0,hap:0, desc:'+25% defense', defense:25},
  {id:'watermill',   name:'Watermill',    era:'medieval', cost:35,  req:'steel',        food:1,prod:2,gold:0,sci:0,cul:0,hap:0, desc:'+1 Food, +2 Prod'},
  {id:'stables',     name:'Stables',      era:'medieval', cost:40,  req:'steel',        food:0,prod:0,gold:0,sci:0,cul:0,hap:0, desc:'+15 XP mounted', xpBonus:15},
  {id:'shipyard',    name:'Shipyard',     era:'medieval', cost:55,  req:'navigation',   food:0,prod:2,gold:0,sci:0,cul:0,hap:0, desc:'+25% naval Prod', needsCoast:true},
  {id:'fort',        name:'Fort',         era:'medieval', cost:55,  req:'steel',        food:0,prod:0,gold:0,sci:0,cul:0,hap:0, desc:'+75% defense, +75 HP', defense:75},
  {id:'bakery',      name:'Bakery',       era:'medieval', cost:30,  req:'civil_service', food:2,prod:0,gold:0,sci:0,cul:0,hap:1, desc:'+2 Food, +1 Happy'},
  {id:'tannery',     name:'Tannery',      era:'medieval', cost:35,  req:'steel',        food:0,prod:1,gold:2,sci:0,cul:0,hap:0, desc:'+1 Prod, +2 Gold'},
  {id:'pub',         name:'Pub',          era:'medieval', cost:35,  req:'civil_service', food:0,prod:0,gold:2,sci:0,cul:0,hap:2, desc:'+2 Gold, +2 Happy'},
  {id:'corner_shop', name:'Corner Shop',  era:'medieval', cost:30,  req:'civil_service', food:1,prod:0,gold:1,sci:0,cul:0,hap:1, desc:'+1 Food, +1 Gold, +1 Happy'},
  // Renaissance
  {id:'observatory', name:'Observatory',  era:'renaissance',cost:65,req:'astronomy',    food:0,prod:0,gold:0,sci:4,cul:0,hap:0, desc:'+4 Science, +50% Science', sciMod:0.50},
  {id:'arsenal',     name:'Arsenal',      era:'renaissance',cost:60,req:'gunpowder',    food:0,prod:2,gold:0,sci:0,cul:0,hap:0, desc:'+2 Prod, city ranged attack', cityRanged:true},
  {id:'theatre',     name:'Theatre',      era:'renaissance',cost:50,req:'printing',     food:0,prod:0,gold:0,sci:0,cul:4,hap:2, desc:'+4 Culture, +2 Happy'},
  {id:'customs_house',name:'Customs House',era:'renaissance',cost:55,req:'economics',   food:0,prod:0,gold:4,sci:0,cul:0,hap:0, desc:'+4 Gold'},
  {id:'museum',      name:'Museum',       era:'renaissance',cost:60,req:'printing',     food:0,prod:0,gold:0,sci:0,cul:2,hap:0, desc:'+2 Culture, +50% History', histMod:0.50},
  {id:'school',      name:'School',       era:'renaissance',cost:45,req:'printing',     food:0,prod:0,gold:0,sci:3,cul:0,hap:0, desc:'+3 Science'},
  {id:'windmill',    name:'Windmill',     era:'renaissance',cost:45,req:'astronomy',    food:0,prod:2,gold:0,sci:0,cul:0,hap:0, desc:'+2 Prod'},
  {id:'printing_house',name:'Printing House',era:'renaissance',cost:50,req:'printing',  food:0,prod:0,gold:0,sci:2,cul:1,hap:0, desc:'+2 Science, +1 Culture'},
  {id:'bastion',     name:'Bastion',      era:'renaissance',cost:55,req:'gunpowder',    food:0,prod:0,gold:0,sci:0,cul:0,hap:0, desc:'+75% defense', defense:75},
  {id:'trade_depot', name:'Trade Depot',  era:'renaissance',cost:45,req:'economics',    food:0,prod:0,gold:3,sci:0,cul:0,hap:0, desc:'+3 Gold'},
  {id:'cannon_foundry',name:'Cannon Foundry',era:'renaissance',cost:60,req:'gunpowder', food:0,prod:2,gold:0,sci:0,cul:0,hap:0, desc:'+25% siege Prod'},
  {id:'apothecary',  name:'Apothecary',   era:'renaissance',cost:40,req:'printing',     food:1,prod:0,gold:0,sci:1,cul:0,hap:0, desc:'+1 Food, +1 Science', growthMod:0.15},
  {id:'post_house',  name:'Post House',   era:'renaissance',cost:35,req:'economics',    food:0,prod:0,gold:1,sci:1,cul:0,hap:0, desc:'+1 Gold, +1 Science'},
  {id:'public_garden',name:'Public Garden',era:'renaissance',cost:40,req:'construction', food:1,prod:0,gold:0,sci:0,cul:1,hap:2, desc:'+1 Food, +1 Culture, +2 Happy'},
  {id:'restaurant',  name:'Restaurant',   era:'renaissance',cost:35,req:'economics',    food:0,prod:0,gold:2,sci:0,cul:1,hap:2, desc:'+2 Gold, +1 Culture, +2 Happy'},
  // Industrial
  {id:'factory',     name:'Factory',      era:'industrial',cost:80, req:'steam_power',  food:0,prod:4,gold:0,sci:0,cul:0,hap:0, desc:'+4 Prod, +25% Prod', prodMod:0.25},
  {id:'hospital',    name:'Hospital',     era:'industrial',cost:70, req:'electricity',  food:0,prod:0,gold:0,sci:0,cul:0,hap:0, desc:'+25% growth', growthMod:0.25},
  {id:'stock_exchange',name:'Stock Exchange',era:'industrial',cost:75,req:'economics',  food:0,prod:0,gold:5,sci:0,cul:0,hap:0, desc:'+5 Gold, +33% Gold', goldMod:0.33},
  {id:'railway_station',name:'Railway Station',era:'industrial',cost:55,req:'industrialization',food:0,prod:2,gold:2,sci:0,cul:0,hap:0, desc:'+2 Prod, +2 Gold'},
  {id:'coal_power',  name:'Coal Power Plant',era:'industrial',cost:70,req:'electricity',food:0,prod:4,gold:0,sci:0,cul:0,hap:-1, desc:'+4 Prod, -1 Happy'},
  {id:'police_station',name:'Police Station',era:'industrial',cost:45,req:'industrialization',food:0,prod:0,gold:0,sci:0,cul:0,hap:1, desc:'+1 Happy, -revolt'},
  {id:'sewage_works',name:'Sewage Works', era:'industrial',cost:55, req:'electricity',  food:2,prod:0,gold:0,sci:0,cul:0,hap:0, desc:'+2 Food, +15% growth', growthMod:0.15},
  {id:'ironworks',   name:'Ironworks',    era:'industrial',cost:80, req:'steam_power',  food:0,prod:4,gold:0,sci:0,cul:0,hap:0, desc:'+4 Prod (1/empire)'},
  {id:'newspaper',   name:'Newspaper',    era:'industrial',cost:40, req:'electricity',  food:0,prod:0,gold:0,sci:0,cul:2,hap:1, desc:'+2 Culture, +1 Happy'},
  {id:'canning_factory',name:'Canning Factory',era:'industrial',cost:50,req:'steam_power',food:2,prod:0,gold:0,sci:0,cul:0,hap:0, desc:'+2 Food'},
  {id:'post_office', name:'Post Office',  era:'industrial',cost:40, req:'industrialization',food:0,prod:0,gold:2,sci:0,cul:1,hap:0, desc:'+2 Gold, +1 Culture'},
  {id:'city_hall',   name:'City Hall',    era:'industrial',cost:60, req:'industrialization',food:0,prod:0,gold:2,sci:0,cul:0,hap:1, desc:'+2 Gold, +1 Happy'},
  {id:'doctors_surgery',name:"Doctor's Surgery",era:'industrial',cost:45,req:'electricity',food:1,prod:0,gold:0,sci:0,cul:0,hap:0, desc:'+1 Food, +10% growth', growthMod:0.10},
  {id:'pharmacy',    name:'Pharmacy',     era:'industrial',cost:40, req:'electricity',  food:1,prod:0,gold:0,sci:0,cul:0,hap:1, desc:'+1 Food, +1 Happy'},
  {id:'department_store',name:'Department Store',era:'industrial',cost:50,req:'industrialization',food:0,prod:0,gold:3,sci:0,cul:0,hap:1, desc:'+3 Gold, +1 Happy'},
  {id:'public_park', name:'Public Park',  era:'industrial',cost:45, req:'industrialization',food:0,prod:0,gold:0,sci:0,cul:1,hap:3, desc:'+1 Culture, +3 Happy'},
  {id:'fire_station',name:'Fire Station', era:'industrial',cost:35, req:'industrialization',food:0,prod:0,gold:0,sci:0,cul:0,hap:1, desc:'+1 Happy'},
  {id:'newsagent',   name:'Newsagent',    era:'industrial',cost:25, req:'industrialization',food:0,prod:0,gold:1,sci:0,cul:1,hap:1, desc:'+1 Gold, +1 Culture, +1 Happy'},
  {id:'zoo',         name:'Zoo',          era:'industrial',cost:55, req:'industrialization',food:0,prod:0,gold:1,sci:1,cul:1,hap:2, desc:'+1 Gold, +1 Science, +1 Culture, +2 Happy'},
  {id:'airfield',    name:'Airfield',     era:'industrial',cost:65, req:'dynamite',     food:0,prod:0,gold:0,sci:0,cul:0,hap:0, desc:'Base 2 air units', airSlots:2},
  // Modern
  {id:'research_lab',name:'Research Lab', era:'modern',    cost:90, req:'electronics',  food:0,prod:0,gold:0,sci:6,cul:0,hap:0, desc:'+6 Science, +50% Science', sciMod:0.50},
  {id:'airport',     name:'Airport',      era:'modern',    cost:85, req:'combustion',   food:0,prod:0,gold:2,sci:0,cul:0,hap:0, desc:'+2 Gold, air unit base', airSlots:4},
  {id:'broadcast_tower',name:'Broadcast Tower',era:'modern',cost:70,req:'electronics',  food:0,prod:0,gold:0,sci:0,cul:4,hap:0, desc:'+4 Culture, +33% Culture', culMod:0.33},
  {id:'stadium',     name:'Stadium',      era:'modern',    cost:75, req:'telecommunications',food:0,prod:0,gold:2,sci:0,cul:0,hap:3, desc:'+3 Happy, +2 Gold'},
  {id:'nuclear_plant',name:'Nuclear Plant',era:'modern',    cost:100,req:'nuclear_fission',food:0,prod:6,gold:0,sci:0,cul:0,hap:0, desc:'+6 Prod'},
  {id:'comms_tower', name:'Comms Tower',  era:'modern',    cost:60, req:'telecommunications',food:0,prod:0,gold:1,sci:2,cul:0,hap:0, desc:'+2 Science, +1 Gold'},
  {id:'supermarket', name:'Supermarket',  era:'modern',    cost:50, req:'electronics',  food:3,prod:0,gold:2,sci:0,cul:0,hap:0, desc:'+3 Food, +2 Gold'},
  {id:'heritage_centre',name:'Heritage Centre',era:'modern',cost:55,req:'electronics',  food:0,prod:0,gold:2,sci:0,cul:2,hap:0, desc:'+3 History, +2 Culture', histMod:0.25},
  {id:'metro_network',name:'Metro Network',era:'modern',   cost:80, req:'electronics',  food:0,prod:3,gold:1,sci:0,cul:0,hap:0, desc:'+3 Prod, +1 Gold'},
  {id:'distribution_centre',name:'Distribution Centre',era:'modern',cost:65,req:'combustion',food:0,prod:2,gold:3,sci:0,cul:0,hap:0, desc:'+2 Prod, +3 Gold'},
  {id:'fuel_station',name:'Fuel Station', era:'modern',    cost:40, req:'combustion',   food:0,prod:1,gold:1,sci:0,cul:0,hap:0, desc:'+1 Prod, +1 Gold'},
  {id:'parking_complex',name:'Parking Complex',era:'modern',cost:35,req:'combustion',   food:0,prod:0,gold:1,sci:0,cul:0,hap:1, desc:'+1 Gold, +1 Happy'},
  {id:'night_club',  name:'Night Club',   era:'modern',    cost:45, req:'electronics',  food:0,prod:0,gold:3,sci:0,cul:0,hap:2, desc:'+3 Gold, +2 Happy'},
  {id:'leisure_centre',name:'Leisure Centre',era:'modern',  cost:50, req:'telecommunications',food:0,prod:0,gold:0,sci:0,cul:1,hap:3, desc:'+1 Culture, +3 Happy', growthMod:0.05},
  {id:'golf_course', name:'Golf Course',  era:'modern',    cost:55, req:'telecommunications',food:0,prod:0,gold:2,sci:0,cul:0,hap:2, desc:'+2 Gold, +2 Happy'},
  {id:'athletics_track',name:'Athletics Track',era:'modern',cost:45,req:'telecommunications',food:0,prod:0,gold:0,sci:0,cul:1,hap:2, desc:'+1 Culture, +2 Happy'},
  {id:'car_dealership',name:'Car Dealership',era:'modern',  cost:40, req:'combustion',   food:0,prod:1,gold:2,sci:0,cul:0,hap:0, desc:'+1 Prod, +2 Gold'},
  {id:'garage',      name:'Garage',       era:'modern',    cost:35, req:'combustion',   food:0,prod:1,gold:0,sci:0,cul:0,hap:0, desc:'+1 Prod, repairs mech units'},
  {id:'takeaway',    name:'Takeaway',     era:'modern',    cost:25, req:'electronics',  food:1,prod:0,gold:1,sci:0,cul:0,hap:1, desc:'+1 Food, +1 Gold, +1 Happy'},
  {id:'cinema',      name:'Cinema',       era:'modern',    cost:45, req:'electronics',  food:0,prod:0,gold:0,sci:0,cul:2,hap:2, desc:'+2 Culture, +2 Happy'},
  {id:'motorway_hub',name:'Motorway Hub', era:'modern',    cost:60, req:'combustion',   food:0,prod:2,gold:2,sci:0,cul:0,hap:0, desc:'+2 Prod, +2 Gold'},
  {id:'television_station',name:'Television Station',era:'modern',cost:55,req:'electronics',food:0,prod:0,gold:2,sci:0,cul:2,hap:0, desc:'+2 Culture, +2 Gold', culMod:0.25},
  {id:'desalination_plant',name:'Desalination Plant',era:'modern',cost:70,req:'electronics',food:3,prod:0,gold:0,sci:0,cul:0,hap:0, desc:'+3 Food (coast)', needsCoast:true},
  {id:'recycling_center',name:'Recycling Center',era:'modern',cost:50,req:'combustion', food:0,prod:1,gold:1,sci:0,cul:0,hap:0, desc:'+1 Prod, +1 Gold'},
  {id:'aa_battery',  name:'AA Battery',   era:'modern',    cost:60, req:'rocketry',     food:0,prod:0,gold:0,sci:0,cul:0,hap:0, desc:'Intercepts air 75%', antiAir:true},
  // AI Era
  {id:'quantum_lab', name:'Quantum Lab',  era:'ai',        cost:110,req:'quantum',      food:0,prod:0,gold:0,sci:8,cul:0,hap:0, desc:'+8 Science, +75% Science', sciMod:0.75},
  {id:'drone_factory',name:'Drone Factory',era:'ai',       cost:90, req:'robotics',     food:0,prod:3,gold:0,sci:0,cul:0,hap:0, desc:'+3 Prod'},
  {id:'neural_hub',  name:'Neural Hub',   era:'ai',        cost:95, req:'ai_tech',      food:0,prod:0,gold:2,sci:2,cul:0,hap:0, desc:'+10% all yields', allMod:0.10},
  {id:'data_centre', name:'Data Centre',  era:'ai',        cost:75, req:'computers',    food:0,prod:0,gold:2,sci:4,cul:0,hap:0, desc:'+4 Science, +2 Gold'},
  {id:'vertical_farm',name:'Vertical Farm',era:'ai',       cost:80, req:'nanotech',     food:5,prod:0,gold:0,sci:0,cul:0,hap:0, desc:'+5 Food, +25% growth', growthMod:0.25},
  {id:'firewall',    name:'Firewall',     era:'ai',        cost:60, req:'computers',    food:0,prod:0,gold:0,sci:0,cul:0,hap:0, desc:'+25% defense vs AI', defense:25},
  {id:'hyperloop_terminal',name:'Hyperloop Terminal',era:'ai',cost:85,req:'ai_tech',    food:0,prod:0,gold:3,sci:0,cul:0,hap:0, desc:'+3 Gold'},
  {id:'autonomous_port',name:'Autonomous Port',era:'ai',   cost:90, req:'ai_tech',      food:0,prod:0,gold:4,sci:0,cul:0,hap:0, desc:'+4 Gold, +50% trade', needsCoast:true, goldMod:0.50},
  {id:'cybersecurity_center',name:'Cybersecurity Center',era:'ai',cost:70,req:'quantum', food:0,prod:0,gold:0,sci:2,cul:0,hap:0, desc:'+2 Science, reveals spies'},
  {id:'smart_grid',  name:'Smart Grid',   era:'ai',        cost:75, req:'computers',    food:0,prod:3,gold:0,sci:0,cul:0,hap:0, desc:'+3 Prod'},
  {id:'heritage_vault',name:'Heritage Vault',era:'ai',     cost:65, req:'ai_tech',      food:0,prod:0,gold:0,sci:0,cul:0,hap:0, desc:'+4 History, +100% legacy', histMod:1.00},
  {id:'ev_chargers', name:'EV Charging Network',era:'ai',  cost:55, req:'robotics',     food:0,prod:2,gold:0,sci:0,cul:0,hap:1, desc:'+2 Prod, +1 Happy'},
  {id:'automated_warehouse',name:'Automated Warehouse',era:'ai',cost:60,req:'robotics', food:0,prod:3,gold:2,sci:0,cul:0,hap:0, desc:'+3 Prod, +2 Gold'},
  {id:'holobar',     name:'Holobar',      era:'ai',        cost:50, req:'ai_tech',      food:0,prod:0,gold:2,sci:0,cul:1,hap:3, desc:'+2 Gold, +1 Culture, +3 Happy'},
  {id:'dark_kitchen',name:'Dark Kitchen',  era:'ai',       cost:40, req:'computers',    food:2,prod:0,gold:2,sci:0,cul:0,hap:0, desc:'+2 Food, +2 Gold'},
  {id:'hypermarket', name:'Hypermarket',   era:'ai',       cost:70, req:'computers',    food:4,prod:0,gold:3,sci:0,cul:0,hap:0, desc:'+4 Food, +3 Gold'},
  {id:'shopping_mall',name:'Shopping Mall', era:'ai',       cost:80, req:'ai_tech',      food:0,prod:0,gold:4,sci:0,cul:0,hap:3, desc:'+4 Gold, +3 Happy', goldMod:0.25},
  // Mars
  {id:'launch_pad',  name:'Launch Pad',   era:'mars',      cost:150,req:'orbital',      food:0,prod:3,gold:0,sci:0,cul:0,hap:0, desc:'+3 Prod, build shuttles'},
  {id:'fusion_reactor',name:'Fusion Reactor',era:'mars',   cost:130,req:'fusion',       food:0,prod:8,gold:0,sci:0,cul:0,hap:0, desc:'+8 Prod'},
  {id:'space_dock',  name:'Space Dock',   era:'mars',      cost:140,req:'orbital',      food:0,prod:3,gold:0,sci:3,cul:0,hap:0, desc:'+3 Prod, +3 Science'},
  {id:'orbital_uplink',name:'Orbital Uplink',era:'mars',   cost:120,req:'orbital',      food:0,prod:0,gold:0,sci:8,cul:0,hap:0, desc:'+100% Science', sciMod:1.00},
  {id:'mars_mission_control',name:'Mars Mission Control',era:'mars',cost:100,req:'orbital',food:0,prod:5,gold:0,sci:0,cul:0,hap:0, desc:'+5 Prod for shuttles'},
  {id:'arcology',    name:'Arcology',     era:'mars',      cost:160,req:'fusion',       food:5,prod:5,gold:0,sci:0,cul:0,hap:3, desc:'+5 Food, +5 Prod, +3 Happy'},
  {id:'space_elevator_terminal',name:'Space Elevator Terminal',era:'mars',cost:120,req:'orbital',food:0,prod:3,gold:3,sci:0,cul:0,hap:0, desc:'-75% space costs'},
];

// Wonders — id, name, era, cost, req (tech), effects
const WONDERS = [
  // Caveman
  {id:'lascaux',      name:'Lascaux Cave Paintings', era:'caveman',   cost:30,  req:'fire',          desc:'+2 Culture all cities', empCulture:2},
  {id:'great_migration',name:'The Great Migration', era:'caveman',   cost:25,  req:'tribal_bonds',  desc:'+3 Mv all units 10 turns'},
  {id:'gobekli_tepe', name:'Göbekli Tepe',          era:'caveman',   cost:35,  req:'stone_knapping', desc:'+3 Culture, +2 Happy', cul:3, empHappy:2},
  // Ancient
  {id:'stonehenge',     name:'Stonehenge',            era:'ancient',    cost:60,  req:'stone_knapping', desc:'+3 Culture all cities', empCulture:3},
  {id:'great_library',  name:'Great Library',         era:'ancient',    cost:80,  req:'writing',        desc:'+1 free tech, +3 Science', freeTech:true, sci:3},
  {id:'pyramids',       name:'Great Pyramid',         era:'ancient',    cost:100, req:'mining',         desc:'+2 Prod all cities', empProd:2},
  {id:'hanging_gardens',name:'Hanging Gardens',       era:'ancient',    cost:75,  req:'agriculture',    desc:'+3 Food all cities', empFood:3},
  {id:'oracle',         name:'Oracle of Delphi',      era:'ancient',    cost:55,  req:'writing',        desc:'+1 free tech, +1 Culture', freeTech:true, empCulture:1},
  // Classical
  {id:'colosseum',      name:'Colosseum',             era:'classical',  cost:90,  req:'construction',   desc:'+4 Happy empire', empHappy:4},
  {id:'parthenon',      name:'Parthenon',             era:'classical',  cost:75,  req:'philosophy',     desc:'+4 Culture this city', cul:4},
  {id:'great_lighthouse',name:'Great Lighthouse',     era:'classical',  cost:85,  req:'construction',   desc:'+1 Mv naval, +2 Gold coastal', needsCoast:true},
  {id:'colossus',       name:'Colossus of Rhodes',    era:'classical',  cost:80,  req:'bronze_working', desc:'+3 Gold, +1 trade route', needsCoast:true},
  {id:'temple_artemis', name:'Temple of Artemis',     era:'classical',  cost:70,  req:'currency',       desc:'+4 Gold all cities', empGold:4},
  {id:'terracotta',     name:'Terracotta Army',       era:'classical',  cost:85,  req:'bronze_working', desc:'+10 XP all units'},
  {id:'petra',          name:'Petra',                  era:'classical',  cost:75,  req:'construction',   desc:'+2 Food, +2 Gold desert tiles'},
  // Medieval
  {id:'great_wall',     name:'Great Wall',            era:'medieval',   cost:120, req:'construction',   desc:'+6 defense all cities', empDef:6},
  {id:'notre_dame',     name:'Notre Dame',            era:'medieval',   cost:100, req:'theology',       desc:'+10 Happy empire', empHappy:10},
  {id:'hagia_sophia',   name:'Hagia Sophia',          era:'medieval',   cost:95,  req:'theology',       desc:'+5 Culture, +3 Happy', cul:5, empHappy:3},
  {id:'angkor_wat',     name:'Angkor Wat',            era:'medieval',   cost:90,  req:'theology',       desc:'+2 Culture, +2 Food', cul:2, food:2},
  {id:'alhambra',       name:'Alhambra',              era:'medieval',   cost:85,  req:'steel',          desc:'Free promotion new units'},
  {id:'chichen_itza',   name:'Chichen Itza',          era:'medieval',   cost:80,  req:'theology',       desc:'Golden Ages +50% longer', cul:3, empHappy:2},
  {id:'machu_picchu',   name:'Machu Picchu',          era:'medieval',   cost:85,  req:'steel',          desc:'+25% trade Money'},
  // Renaissance
  {id:'printing_press', name:'Printing Press',        era:'renaissance',cost:90,  req:'printing',       desc:'-10% tech cost', techDiscount:0.10},
  {id:'sistine_chapel', name:'Sistine Chapel',        era:'renaissance',cost:100, req:'theology',       desc:'+5 Culture all cities', empCulture:5},
  {id:'taj_mahal',      name:'Taj Mahal',             era:'renaissance',cost:95,  req:'economics',      desc:'+10 Happy, Golden Age', empHappy:10, goldenAge:true},
  {id:'magellans',      name:"Magellan's Expedition", era:'renaissance',cost:80,  req:'colonialism',    desc:'+2 Mv naval'},
  {id:'forbidden_city', name:'Forbidden City',        era:'renaissance',cost:90,  req:'printing',       desc:'-50% corruption all cities'},
  {id:'versailles',     name:'Versailles',            era:'renaissance',cost:100, req:'printing',       desc:'+5 Culture, +5 Happy', cul:5, empHappy:5},
  {id:'globe_theatre',  name:'Globe Theatre',         era:'renaissance',cost:75,  req:'printing',       desc:'+4 Culture, +2 Happy', cul:4, empHappy:2},
  // Industrial
  {id:'big_ben',        name:'Big Ben',               era:'industrial', cost:100, req:'economics',      desc:'-15% rush buy cost', rushDiscount:0.15},
  {id:'eiffel_tower',   name:'Eiffel Tower',          era:'industrial', cost:110, req:'steam_power',    desc:'+10 Culture, +15 diplomacy', empCulture:10},
  {id:'statue_liberty', name:'Statue of Liberty',     era:'industrial', cost:95,  req:'steam_power',    desc:'+1 Prod all cities, +4 Happy', empProd:1, empHappy:4},
  {id:'suez_canal',     name:'Suez Canal',            era:'industrial', cost:120, req:'dynamite',       desc:'+2 Mv naval, +3 Gold coastal', needsCoast:true},
  {id:'panama_canal',   name:'Panama Canal',          era:'industrial', cost:130, req:'dynamite',       desc:'+50% trade Money', needsCoast:true},
  {id:'christ_redeemer',name:'Christ the Redeemer',   era:'industrial', cost:85,  req:'steam_power',    desc:'+5 Happy, -50% war weariness', empHappy:5},
  {id:'golden_gate',    name:'Golden Gate Bridge',    era:'industrial', cost:90,  req:'steam_power',    desc:'+3 Gold, +2 Prod', needsCoast:true},
  // Modern
  {id:'manhattan',      name:'Manhattan Project',     era:'modern',     cost:120, req:'nuclear_fission',desc:'Enables nukes', nukes:true},
  {id:'united_nations', name:'United Nations',        era:'modern',     cost:100, req:'telecommunications',desc:'Diplomatic victory path', diplomatic:true},
  {id:'apollo',         name:'Apollo Program',        era:'modern',     cost:120, req:'rocketry',       desc:'Reveals map, Mars tech', revealMap:true},
  {id:'sydney_opera',   name:'Sydney Opera House',    era:'modern',     cost:85,  req:'electronics',    desc:'+5 Culture, +25% Culture', cul:5, culMod:0.25},
  {id:'hoover_dam',     name:'Hoover Dam',            era:'modern',     cost:100, req:'electricity',    desc:'+6 Prod'},
  {id:'iss',            name:'Int. Space Station',    era:'modern',     cost:130, req:'rocketry',       desc:'+10 Science, +2 Sci all cities', sci:10, empScience:2},
  {id:'lhc',            name:'Large Hadron Collider', era:'modern',     cost:140, req:'nuclear_fission',desc:'Free tech, +75% Science', freeTech:true, sciMod:0.75},
  // AI Era
  {id:'internet',       name:'Internet',              era:'ai',         cost:110, req:'computers',      desc:'+2 Science all cities', empScience:2},
  {id:'singularity',    name:'The Singularity',       era:'ai',         cost:160, req:'quantum',        desc:'+100% Science 20 turns', sciBoost:true},
  {id:'global_network', name:'Global Network',        era:'ai',         cost:130, req:'computers',      desc:'+3 Gold/trade, +1 Sci/city', empScience:1},
  {id:'dyson_sphere',   name:'Dyson Sphere Prototype',era:'ai',        cost:150, req:'nanotech',       desc:'+10 Prod this city, +2 Prod all', empProd:2},
  {id:'quantum_internet',name:'Quantum Internet',     era:'ai',        cost:120, req:'quantum',        desc:'+50% Science all cities', sciMod:0.50},
  {id:'machine_consciousness',name:'Machine Consciousness',era:'ai',   cost:140, req:'quantum',        desc:'+5% all yields', allMod:0.05},
  {id:'orbital_ring',   name:'Orbital Ring',          era:'ai',         cost:160, req:'nanotech',       desc:'+5 Prod all cities', empProd:5},
  // Mars
  {id:'space_elevator', name:'Space Elevator',        era:'mars',       cost:200, req:'orbital',        desc:'-50% shuttle cost', shuttleDiscount:0.50},
  {id:'mars_colony_alpha',name:'Mars Colony Alpha',   era:'mars',       cost:250, req:'mars_colony',    desc:'1st Mars victory module'},
  {id:'terraforming',   name:'Terraforming Engine',   era:'mars',       cost:200, req:'fusion',         desc:'+25% all yields empire', allMod:0.25},
  {id:'ark',            name:'Ark of Civilization',   era:'mars',       cost:180, req:'orbital',        desc:'+100% History all cities', histMod:1.00},
];

// Unit types — id, name, era, domain, str, rng, mv, cost, req (tech), type
const UNIT_TYPES = [
  // Civilians
  {id:'gatherer',  name:'Gatherer',  era:'caveman',   domain:'land', str:0, rng:0, mv:2, cost:10, req:'foraging',   type:'civilian', canBuild:true},
  {id:'nomad',     name:'Nomad',     era:'caveman',   domain:'land', str:0, rng:0, mv:3, cost:15, req:'tribal_bonds',type:'settler',  founds:'hamlet'},
  {id:'worker',    name:'Worker',    era:'ancient',   domain:'land', str:0, rng:0, mv:2, cost:20, req:'mining',      type:'civilian', canBuild:true},
  {id:'settler',   name:'Settler',   era:'ancient',   domain:'land', str:0, rng:0, mv:2, cost:40, req:'agriculture', type:'settler',  founds:'city', popCost:1},
  // Caveman Military
  {id:'club_warrior',name:'Club Warrior',era:'caveman',domain:'land', str:5,  rng:0, mv:2, cost:8,  req:'fire',       type:'melee'},
  {id:'rock_thrower',name:'Rock Thrower',era:'caveman',domain:'land', str:3,  rng:4, mv:2, cost:8,  req:'stone_knapping',type:'ranged'},
  {id:'scout',     name:'Scout',     era:'caveman',   domain:'land', str:3,  rng:0, mv:4, cost:10, req:'tribal_bonds',type:'recon'},
  // Caveman Naval
  {id:'log_raft',  name:'Log Raft',  era:'caveman',   domain:'sea',  str:2,  rng:0, mv:2, cost:8,  req:'toolcraft',  type:'naval_melee', capacity:1},
  // Ancient Military
  {id:'warrior',   name:'Warrior',   era:'ancient',   domain:'land', str:10, rng:0, mv:2, cost:15, req:'bronze_working',type:'melee'},
  {id:'spearman',  name:'Spearman',  era:'ancient',   domain:'land', str:12, rng:0, mv:2, cost:18, req:'bronze_working',type:'anti_cav'},
  {id:'archer',    name:'Archer',    era:'ancient',   domain:'land', str:5,  rng:8, mv:2, cost:16, req:'archery',   type:'ranged'},
  {id:'horseman',  name:'Horseman',  era:'ancient',   domain:'land', str:14, rng:0, mv:4, cost:25, req:'animal_husbandry',type:'mounted', resReq:'horses'},
  {id:'galley',    name:'Galley',    era:'ancient',   domain:'sea',  str:8,  rng:0, mv:3, cost:20, req:'sailing',   type:'naval_melee', capacity:2},
  {id:'war_canoe', name:'War Canoe', era:'ancient',   domain:'sea',  str:6,  rng:0, mv:3, cost:15, req:'sailing',   type:'hybrid', amphibious:true},
  // Classical
  {id:'swordsman', name:'Swordsman', era:'classical', domain:'land', str:18, rng:0, mv:2, cost:25, req:'iron_working',type:'melee', resReq:'iron'},
  {id:'catapult',  name:'Catapult',  era:'classical', domain:'land', str:5,  rng:12,mv:2, cost:28, req:'mathematics',type:'siege'},
  {id:'trireme',   name:'Trireme',   era:'classical', domain:'sea',  str:14, rng:0, mv:4, cost:30, req:'iron_working',type:'naval_melee'},
  {id:'bireme',    name:'Bireme',    era:'classical', domain:'sea',  str:10, rng:12,mv:3, cost:28, req:'mathematics',type:'naval_ranged'},
  // Medieval
  {id:'longswordsman',name:'Longswordsman',era:'medieval',domain:'land',str:24,rng:0,mv:2,cost:35,req:'steel',type:'melee', resReq:'iron'},
  {id:'crossbowman',name:'Crossbowman',era:'medieval',domain:'land', str:10, rng:18,mv:2, cost:30, req:'steel',     type:'ranged'},
  {id:'knight',    name:'Knight',    era:'medieval',   domain:'land', str:28, rng:0, mv:4, cost:45, req:'steel',     type:'mounted', resReq:'horses'},
  {id:'trebuchet', name:'Trebuchet', era:'medieval',   domain:'land', str:8,  rng:18,mv:2, cost:38, req:'steel',     type:'siege'},
  {id:'caravel',   name:'Caravel',   era:'medieval',   domain:'sea',  str:22, rng:0, mv:5, cost:35, req:'navigation',type:'naval_melee'},
  {id:'pikeman',   name:'Pikeman',   era:'medieval',   domain:'land', str:20, rng:0, mv:2, cost:30, req:'steel',     type:'anti_cav'},
  {id:'cog',       name:'Cog',       era:'medieval',   domain:'sea',  str:18, rng:0, mv:4, cost:32, req:'navigation',type:'naval_melee', capacity:3},
  {id:'fire_ship', name:'Fire Ship', era:'medieval',   domain:'sea',  str:12, rng:0, mv:5, cost:20, req:'navigation',type:'naval_melee'},
  {id:'landing_barge',name:'Landing Barge',era:'medieval',domain:'sea',str:10,rng:0, mv:3, cost:25, req:'navigation',type:'hybrid', amphibious:true},
  // Renaissance
  {id:'musketman', name:'Musketman', era:'renaissance',domain:'land', str:30, rng:0, mv:2, cost:45, req:'gunpowder', type:'melee'},
  {id:'cannon',    name:'Cannon',    era:'renaissance',domain:'land', str:12, rng:24,mv:2, cost:50, req:'gunpowder', type:'siege'},
  {id:'frigate',   name:'Frigate',   era:'renaissance',domain:'sea',  str:18, rng:28,mv:5, cost:55, req:'colonialism',type:'naval_ranged'},
  {id:'marine',    name:'Marine',    era:'renaissance',domain:'land', str:26, rng:0, mv:2, cost:40, req:'colonialism',type:'melee', amphibious:true},
  {id:'lancer',    name:'Lancer',    era:'renaissance',domain:'land', str:28, rng:0, mv:5, cost:45, req:'gunpowder', type:'mounted', resReq:'horses'},
  {id:'privateer', name:'Privateer', era:'renaissance',domain:'sea',  str:25, rng:0, mv:5, cost:45, req:'colonialism',type:'naval_melee'},
  // Industrial
  {id:'rifleman',  name:'Rifleman',  era:'industrial', domain:'land', str:40, rng:0, mv:2, cost:55, req:'industrialization',type:'melee'},
  {id:'cavalry',   name:'Cavalry',   era:'industrial', domain:'land', str:38, rng:0, mv:5, cost:60, req:'rifling',   type:'mounted', resReq:'horses'},
  {id:'artillery', name:'Artillery', era:'industrial', domain:'land', str:15, rng:36,mv:2, cost:65, req:'dynamite',  type:'siege'},
  {id:'ironclad',  name:'Ironclad',  era:'industrial', domain:'sea',  str:35, rng:0, mv:4, cost:70, req:'steam_power',type:'naval_melee', resReq:'coal'},
  {id:'gatling_gun',name:'Gatling Gun',era:'industrial',domain:'land',str:20, rng:30,mv:2, cost:55, req:'rifling',   type:'ranged'},
  {id:'destroyer', name:'Destroyer', era:'industrial', domain:'sea',  str:30, rng:32,mv:6, cost:75, req:'steam_power',type:'naval_ranged'},
  {id:'transport_ship',name:'Transport Ship',era:'industrial',domain:'sea',str:15,rng:0,mv:5,cost:50,req:'steam_power',type:'naval_melee', capacity:4},
  {id:'observation_balloon',name:'Observation Balloon',era:'industrial',domain:'air',str:0,rng:0,mv:4,cost:30,req:'dynamite',type:'recon'},
  {id:'amphibious_barge',name:'Amphibious Gun Barge',era:'industrial',domain:'sea',str:25,rng:28,mv:3,cost:60,req:'steam_power',type:'hybrid', amphibious:true},
  // Modern
  {id:'infantry',  name:'Infantry',  era:'modern',     domain:'land', str:50, rng:0, mv:2, cost:70, req:'combustion', type:'melee'},
  {id:'tank',      name:'Tank',      era:'modern',     domain:'land', str:55, rng:0, mv:5, cost:90, req:'combustion', type:'armor', resReq:'oil'},
  {id:'rocket_artillery',name:'Rocket Artillery',era:'modern',domain:'land',str:20,rng:46,mv:2,cost:80,req:'rocketry',type:'siege'},
  {id:'fighter',   name:'Fighter',   era:'modern',     domain:'air',  str:45, rng:0, mv:10,cost:80, req:'flight',    type:'air_fighter', resReq:'oil'},
  {id:'bomber',    name:'Bomber',    era:'modern',     domain:'air',  str:35, rng:55,mv:8, cost:85, req:'flight',    type:'air_bomber', resReq:'oil'},
  {id:'battleship',name:'Battleship',era:'modern',     domain:'sea',  str:50, rng:48,mv:5, cost:100,req:'combustion', type:'naval_ranged', resReq:'oil'},
  {id:'submarine', name:'Submarine', era:'modern',     domain:'sea',  str:45, rng:0, mv:4, cost:85, req:'electronics',type:'naval_stealth'},
  {id:'machine_gun',name:'Machine Gun',era:'modern',   domain:'land', str:30, rng:40,mv:2, cost:65, req:'combustion', type:'ranged'},
  {id:'paratrooper',name:'Paratrooper',era:'modern',   domain:'land', str:45, rng:0, mv:2, cost:75, req:'flight',    type:'melee', amphibious:true},
  {id:'aircraft_carrier',name:'Aircraft Carrier',era:'modern',domain:'sea',str:30,rng:0,mv:5,cost:120,req:'flight',type:'naval_capital', resReq:'oil', airSlots:3},
  {id:'tactical_nuke',name:'Tactical Nuke',era:'modern',domain:'air', str:0,  rng:60,mv:0, cost:200,req:'nuclear_fission',type:'special', resReq:'uranium'},
  {id:'seaplane',  name:'Seaplane',  era:'modern',     domain:'air',  str:35, rng:40,mv:8, cost:75, req:'flight',    type:'hybrid'},
  // AI Era
  {id:'cyber_infantry',name:'Cyber Infantry',era:'ai', domain:'land', str:65, rng:0, mv:3, cost:90, req:'ai_tech',   type:'melee'},
  {id:'mech_walker',name:'Mech Walker',era:'ai',       domain:'land', str:70, rng:0, mv:4, cost:110,req:'robotics',  type:'armor'},
  {id:'drone_swarm',name:'Drone Swarm',era:'ai',       domain:'air',  str:55, rng:50,mv:12,cost:70, req:'robotics',  type:'air_fighter'},
  {id:'railgun',   name:'Railgun',   era:'ai',         domain:'land', str:25, rng:60,mv:2, cost:95, req:'ai_tech',   type:'siege'},
  {id:'stealth_bomber',name:'Stealth Bomber',era:'ai', domain:'air',  str:40, rng:70,mv:10,cost:100,req:'ai_tech',   type:'air_bomber'},
  {id:'autonomous_sub',name:'Autonomous Sub',era:'ai', domain:'sea',  str:60, rng:0, mv:6, cost:95, req:'robotics',  type:'naval_stealth'},
  {id:'assault_vtol',name:'Assault VTOL',era:'ai',     domain:'air',  str:55, rng:45,mv:8, cost:90, req:'robotics',  type:'hybrid'},
  {id:'hovercraft', name:'Hovercraft',era:'ai',        domain:'sea',  str:50, rng:0, mv:6, cost:85, req:'robotics',  type:'hybrid', amphibious:true, capacity:2},
  {id:'cyber_ops', name:'Cyber Ops', era:'ai',         domain:'land', str:0,  rng:0, mv:2, cost:80, req:'ai_tech',   type:'special'},
  {id:'icbm',      name:'ICBM',      era:'ai',         domain:'air',  str:0,  rng:999,mv:0,cost:300,req:'quantum',   type:'special', resReq:'uranium'},
  // Mars
  {id:'titan_mech',name:'Titan Mech',  era:'mars',     domain:'land', str:90, rng:0, mv:3, cost:150,req:'nanotech',  type:'armor'},
  {id:'mars_shuttle',name:'Mars Shuttle',era:'mars',    domain:'air',  str:0,  rng:0, mv:0, cost:300,req:'mars_colony',type:'victory'},
  {id:'exo_soldier',name:'Exo Soldier', era:'mars',    domain:'land', str:80, rng:0, mv:4, cost:120,req:'nanotech',  type:'melee'},
  {id:'plasma_artillery',name:'Plasma Artillery',era:'mars',domain:'land',str:30,rng:75,mv:2,cost:130,req:'fusion',type:'siege'},
  {id:'hypersonic',name:'Hypersonic Interceptor',era:'mars',domain:'air',str:70,rng:0,mv:15,cost:140,req:'orbital',type:'air_fighter'},
  {id:'orbital_drone',name:'Orbital Strike Drone',era:'mars',domain:'air',str:50,rng:85,mv:99,cost:160,req:'orbital',type:'air_bomber'},
  {id:'fusion_battlecruiser',name:'Fusion Battlecruiser',era:'mars',domain:'sea',str:75,rng:70,mv:7,cost:180,req:'fusion',type:'naval_capital', airSlots:4},
  {id:'ekranoplan',name:'Ekranoplan', era:'mars',      domain:'sea',  str:65, rng:55,mv:8, cost:150,req:'fusion',    type:'hybrid', amphibious:true},
];

// Difficulty levels
const DIFFICULTY = [
  {id:0, name:'Amoeba',           emoji:'🦠', pRes:1.50, pDev:1.40, aiRes:0.50, aiDev:0.60, aiCombat:0.70, startBonus:null, scoreMul:0.50},
  {id:1, name:'Invertebrate',     emoji:'🐛', pRes:1.30, pDev:1.25, aiRes:0.70, aiDev:0.75, aiCombat:0.80, startBonus:null, scoreMul:0.60},
  {id:2, name:'Wolf',             emoji:'🐺', pRes:1.15, pDev:1.10, aiRes:0.85, aiDev:0.90, aiCombat:0.90, startBonus:null, scoreMul:0.75},
  {id:3, name:'Neanderthal',      emoji:'🧬', pRes:1.05, pDev:1.05, aiRes:0.95, aiDev:0.95, aiCombat:1.00, startBonus:null, scoreMul:0.90},
  {id:4, name:'Homo Sapiens',     emoji:'🧑', pRes:1.00, pDev:1.00, aiRes:1.00, aiDev:1.00, aiCombat:1.00, startBonus:null, scoreMul:1.00},
  {id:5, name:'Apex Predator',    emoji:'🦅', pRes:1.00, pDev:1.00, aiRes:1.15, aiDev:1.10, aiCombat:1.10, startBonus:{settlers:1,warriors:1}, scoreMul:1.25},
  {id:6, name:'Superintelligence', emoji:'🧠', pRes:0.90, pDev:0.95, aiRes:1.30, aiDev:1.20, aiCombat:1.15, startBonus:{settlers:2,warriors:2,techs:1}, scoreMul:1.50},
  {id:7, name:'Singularity AI',   emoji:'🤖', pRes:0.80, pDev:0.90, aiRes:1.50, aiDev:1.35, aiCombat:1.20, startBonus:{settlers:2,warriors:3,techs:2,gold:100}, scoreMul:2.00},
];

// City tier thresholds
const CITY_TIERS = [
  {name:'Hamlet',      pop:1,  radius:1, slots:3,  emoji:'🛖'},
  {name:'Village',     pop:4,  radius:1, slots:6,  emoji:'🏘️'},
  {name:'Town',        pop:8,  radius:2, slots:9,  emoji:'🏠'},
  {name:'City',        pop:14, radius:2, slots:13, emoji:'🏙️'},
  {name:'Conurbation', pop:23, radius:3, slots:17, emoji:'🌇'},
  {name:'Metropolis',  pop:35, radius:3, slots:22, emoji:'🌆'},
];

// City names pool
const CITY_NAMES = [
  'Alexandria','Rome','Athens','Babylon','Memphis','Thebes','Carthage','Persepolis','Sparta','Troy',
  'Constantinople','Londinium','Lutetia','Vindobona','Mediolanum','Cordoba','Damascus','Samarkand',
  'Beijing','Kyoto','Delhi','Cusco','Tenochtitlan','Ur','Nineveh','Palmyra','Angkor','Lhasa',
  'Timbuktu','Zanzibar','Novgorod','Vienna','Florence','Venice','Bruges','Toledo','Stockholm',
  'Lisbon','Dublin','Edinburgh','Prague','Budapest','Warsaw','Oslo','Helsinki','Reykjavik',
  'Cairo','Baghdad','Isfahan','Mecca','Marrakesh','Fez','Tunis','Algiers','Tripoli','Beirut',
  'Hanoi','Manila','Jakarta','Bangkok','Singapore','Sydney','Auckland','Lima','Bogota','Havana',
  'Quebec','Boston','Philadelphia','Charleston','Nairobi','Accra','Lagos','Kinshasa','Addis Ababa',
  'Osaka','Seville','Hamburg','Gdansk','Bruges','Saigon','Muscat','Riga','Tallinn','Tbilisi',
  'Baku','Ulaanbaatar','Kathmandu','Quito','Montevideo','Santiago','Yangon','Colombo','Maputo',
  'Windhoek','Antananarivo','Valletta','Dubrovnik','Split','Aleppo'
];
